export const DEFAULT_GAME_OPTIONS = {
  gameTheme: 'numbers',
  numberOfPlayers: '1',
  gridSize: '4x4',
};

export const GAME_SEED = {
  numbers: [
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
    '11',
    '12',
    '13',
    '14',
    '15',
    '16',
    '17',
    '18',
  ],
  icons: [
    'ri-star-smile-line',
    'ri-fire-line',
    'ri-lightbulb-flash-line',
    'ri-rocket-2-line',
    'ri-gift-line',
    'ri-gamepad-line',
    'ri-chess-line',
    'ri-heart-3-line',
    'ri-ghost-line',
    'ri-skull-line',
    'ri-sword-line',
    'ri-treasure-map-line',
    'ri-dragons-line',
    'ri-magic-line',
    'ri-bear-smile-line',
    'ri-cake-2-line',
    'ri-football-line',
    'ri-music-2-line',
  ],
};
